accounts/urls.py
from django.urls import path
from .views import (UserSignupView, LoginViews, AcceptCodeView, ProfileView, LogOutView \
    ,UserPasswordResetView, UserPasswordResetCompleteView, UserPasswordResetConfirmView, UserPasswordResetDoneView,
                    EditProfileView)
app_name = 'accounts'
urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', LoginViews.as_view(), name='login'),
    path('accept_code/', AcceptCodeView.as_view(), name='accept_code'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='edit_profile'),
    path('profile/logout/', LogOutView.as_view(), name='logout'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import AllPostBlog, BlogDetailsView, LatestBlogPostView


app_name = 'blog'
urlpatterns = [
    path('blog/', AllPostBlog.as_view(), name='all_posts'),
    path('blog_details/<slug:slug>/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),
    # path('all_category/', CategoryBlogView.as_view(), name='category'),
    path('latest_post/', LatestBlogPostView.as_view(), name='latest_post'),
    path('slug/<slug:category_slug>/', AllPostBlog.as_view(), name='post_by_category')
]

doctor/urls.py
from django.urls import path
from .views import  HomeComponents, SignUpDoctorView, All_doctor \
    ,DoctorSlider, LatesDoctor, AdvanceSearchDoctorView, AppointmentDoctorView, DetailsQuestionDoctorView

app_name = 'doctor'
urlpatterns = [
    path('', HomeComponents.as_view(), name='home'),
    path('signup_doctor/', SignUpDoctorView.as_view(), name='signup_doctor'),
    path('list_doctor/', All_doctor.as_view(), name='all_doctor'),
    # path('doctor_slider/', DoctorSlider.as_view(), name='doctor_slider'),
    path('latest_doctor', LatesDoctor.as_view(), name='latest_doctor'),
    # path('advance_search_doctor/', AdvanceSearchDoctorView.as_view(), name='advance_search_doctor'),
    path('details_doctor/<int:doctor_id>/', AppointmentDoctorView.as_view(), name='order_details_doctor'),
]

kine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('doctor.urls', namespace='doctor')),
    path('', include('sites.urls', namespace='sites')),
    path('', include('blog.urls', namespace='blog')),
    # path('', include('orders.urls', namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sites/urls.py
from django.urls import path
from .views import FooterComponents, HeaderComponenets, contactUsView, FeedbackView, AboutUsView, BucketView

app_name = 'sites'
urlpatterns = [
    path('hrader_components', HeaderComponenets.as_view(), name='hrader_components'),
    path('footer_components', FooterComponents.as_view(), name='footer_components'),
    path('contact_us/', contactUsView.as_view(), name='contact_us'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('buckets/', BucketView.as_view(), name='buckets'),
]

sites/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from common.models import CreateAt, UpdateAt


class SiteSettings(models.Model):
    site_name = models.CharField(_('Site Name'), max_length=200, unique=True)
    site_url = models.URLField(_('Site URL'), max_length=200)
    site_logo = models.ImageField(_('Site Logo'), upload_to='site/logo/%Y/%M/%d')
    phone = models.CharField(_('Phone'), max_length=15, blank=True, null=True)
    landing_phone = models.CharField(_('Landing Phone'), max_length=15, blank=True, null=True)
    fax = models.CharField(_('Fax'), max_length=15, blank=True, null=True)
    email = models.EmailField(_('Email'), max_length=100, blank=True, null=True)
    copy_write = models.TextField(_('Copy write'))
    is_main_setting = models.BooleanField(_('Is main setting'), default=False)
    address = models.TextField(_('Address'))
    abour_us_text = models.TextField(_('Abour Text'), blank=True, null=True)
    
    def __str__(self) -> str:
        return self.site_name
    
    class Meta:
        db_table = 'site_settings'
        verbose_name = 'site setting'
        verbose_name_plural = 'site settings'


class Feedback(CreateAt):
    title = models.CharField(_("Title"), max_length=100)
    email = models.EmailField(_("Email"), max_length=100)
    body = models.TextField(_("Body"))
    be_answeraed = models.BooleanField(_("Answeraed"), default=True)
    
    def __str__(self) -> str:
        return f'{self.title} -- {self.email} -- {self.be_answeraed}'
    
    class Meta:
        db_table = 'feedback'
        verbose_name = _('feedback')
        verbose_name_plural = _('feedback')


class PermisionSite(CreateAt, UpdateAt):
    permission_url = models.URLField(_("url"), max_length=200)
    image = models.ImageField(_("image"), upload_to='site/permissions/%Y/%M/%d')
    description = models.TextField(_("Description"), blank=True, null=True)
    is_active  = models.BooleanField(_("is_active"), default=True)
    
    class Meta:
        db_table = 'permissions'
        verbose_name = _('permissions')
        verbose_name_plural = _('permissions')


class AboutUs(CreateAt, UpdateAt):
    title = models.CharField(_("title"), max_length=200)
    image = models.ImageField(_("image"), upload_to='about-us/%Y/%M/%d', blank=True, null=True)
    description = models.TextField()
    is_active = models.BooleanField(_("is active"), default=True)
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        db_table = 'about-us'
        verbose_name = _("About Us")
        verbose_name_plural = _("About Us")


class SciolAboutUs(CreateAt, UpdateAt):
    url = models.URLField(_('sciol name url'), max_length=254)
    title = models.CharField(_('title'), max_length=100)
    is_active = models.BooleanField(_('is active'), default=True)
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        db_table = 'sciol-about-us'
        verbose_name = _("sciol")
        verbose_name_plural = _("sciol")

sites/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.views import View
from django.views.generic import TemplateView, ListView
from django.contrib import messages
from .form import FeedbackForm
from .models import Feedback, SiteSettings, PermisionSite, AboutUs, SciolAboutUs


class contactUsView(View):
    template_name = 'sites/contact_us.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class HeaderComponenets(View):
    template_name = 'sites/header.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class FooterComponents(View):
    template_name = 'sites/footer.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class FeedbackView(View):
    form_class = FeedbackForm
    template_name = 'sites/feedback.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            Feedback.objects.create(**form.cleaned_data)
            messages.success(request, 'tnx your feedback', 'success')
            return redirect('sites:contact_us')
        return render(request, self.template_name, {'form': form})


class LogoDescriptionFooterComponents(View):
    def get(self, request, *args, **kwargs):
        logo_desc_foot = get_object_or_404(SiteSettings, is_main_setting=True)
        return render(request, 'sites/logo_description_footer.html', {'logo_desc_foot': logo_desc_foot})


class ENemadView(View):
    def get(self, request, *args, **kwargs):
        e_nemad = get_list_or_404(PermisionSite, is_active=True)
        return render(request, 'sites/e_nemad.html', {'e_nemad': e_nemad})


class WaysOfComunicarion(View):
    def get(self, request, *args, **kwargs):
        woc = get_object_or_404(SiteSettings, is_main_setting=True)
        return render(request, 'sites/woc.html', {'woc': woc})


class SliderComponenets(TemplateView):
    template_name = 'sites/slider.html'


class AboutUsView(ListView):
    model = AboutUs
    template_name = 'sites/about_us.html'
    context_object_name = 'about_us'
    queryset = AboutUs.objects.filter(is_active=True)


class SciolAboutUsView(ListView):
    model = SciolAboutUs
    queryset = SciolAboutUs.objects.filter(is_active=True)
    template_name = 'sites/sciol_about_us.html'
    context_object_name = 'sciol_about_us'


# TODO
class BucketView(View):
    templte_name = 'sites/bucket.html'

    def get(self, request, *args, **kwargs):
        pass

sites/templates/sites/about_us.html
{% extends "base/base.html" %}

{% load static %}

{% load render_partial %}

{% block title %}
<title>درباره ما</title>
{% endblock title %}

{% block content %}
<section class="px-6 mt-4 mb-8">
    <div class="container mx-auto max-w-screen-xl">
      <div class="bg-white p-3 rounded-3xl mb-4">
        <div class="text-sm breadcrumbs">
          <ul>
            <li><a>خانه</a></li> 
            <li>درباره ما</li>
          </ul>
        </div>
      </div>
      <div class="bg-white rounded-3xl p-6">
        <div class="p-3 bg-stone-200 rounded-xl mb-4">
          <h1 class="text-sm font-YekanBakh-Bold">درباره ما</h1>
        </div>
        {% for about in about_us %}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-14 pt-8">
          <div class="leading-8">
            <h2 class="text-lg font-YekanBakh-Bold mb-4">درباره kine بخوانید...</h2>
            <p class='mt-4'>{{ about.description }}</p>
          </div>
          <div>
            <img class="rounded-2xl" src="{{ about.image.url }}" alt="" style="height: 23rem;">
          </div>
        </div>
        {% endfor %}
        {% render_partial 'sites.views.SciolAboutUsView' %}
      </div>
    </div>
  </section>
{% endblock content %}

sites/templates/sites/bucket.html
{% extends 'base/base.html' %}

{% block title %}
	<title>صندوقچه دانلود</title>
{% endblock %}

{% block content %}

{% endblock %}

sites/templates/sites/contact_us.html
{% extends "base/base.html" %}

{% load render_partial %}

{% block title %}
<title>ارتباط با ما</title>
{% endblock title %}

{% block content %}
<div class="grid grid-cols-1 md:grid-cols-2 gap-14 pt-8">
  <div>
    <p class="mb-4">جهت ارتباط با ما و ارسال نظرات و پیشنهادات خود می توانید از فرم زیر استفاده نمایید.</p>
    {% render_partial 'sites.views.FeedbackView' %}
  </div>
  <div>
    {% render_partial 'sites.views.WaysOfComunicarion' %}

    </div>
  </div>
</div>
{% endblock content %}

sites/templates/sites/e_nemad.html
<div>
    <div class="swiper partners swiper-initialized swiper-horizontal swiper-rtl swiper-backface-hidden">
      <div class="swiper-wrapper" id="swiper-wrapper-c296551ef67cdbd1" aria-live="polite">
        {% for e in e_nemad %}
        <div class="swiper-slide swiper-slide-active" role="group" aria-label="1 / 5" style="width: 101.8px; margin-left: 10px;">
            <a href='{{ e.url }}'><img src="{{ e.image.url }}" alt=""></a>
          </div>  
        {% endfor %}

      </div>
    <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span><span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
  
  </div>

sites/templates/sites/feedback.html
<div class="form-control w-full">
    <form action='/feedback/' method='post'>
        {{ form }}
        {% csrf_token %}
        <button type='submit' class="btn bg-stone-800 w-36 hover:bg-stone-900 text-white my-3">ارسال پیام</button>
    </form>
</div>

sites/templates/sites/footer.html
{% load static %}

{% load render_partial %}

<footer class="p-10 bg-stone-800 text-white">
    <div class="container mx-auto max-w-screen-xl">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 border-b-2 pb-10 mb-10 border-stone-700">
          
          {% render_partial 'sites.views.LogoDescriptionFooterComponents' %}
          
          {% render_partial 'sites.views.ENemadView' %}
        </div>
        <div class="grid grid-cols-12 gap-4 leading-8">
            
            <div class="col-span-6 lg:col-span-2 text-right">
                <h3 class="font-YekanBakh-Bold text-white mb-4 text-lg">دسترسی سریع</h3>
                <ul>
                    <li><a href="{% url "doctor:home" %}">صفحه اصلی</a></li>
                    <li><a href="{% url "doctor:all_doctor" %}">لیست پزشکان</a></li>
                    <li><a href="reservation.html">رزرو نوبت</a></li>
                    <li><a href="{% url "sites:contact_us" %}">تماس با ما</a></li>
                    <li><a href="{% url "blog:all_posts" %}">وبلاگ</a></li>
                </ul>
            </div>
            <div class="col-span-6 lg:col-span-2 text-right">
                <h3 class="font-YekanBakh-Bold text-white mb-4 text-lg">خدمات ویزیت</h3>
                <ul>
                    <li><a href="{% url "sites:about_us" %}">درباره ما</a></li>
                    <li><a href="question.html">سوالات متداول</a></li>
                    <li><a href="single-blog.html">صفحه داخلی بلاگ</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href='#'>پروفایل کاربری</a></li>
                    {% else %}
                    <li><a href="login.html">ورود</a></li>
                    <li><a href="sign-up.html">ثبت نام</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-span-6 lg:col-span-2 text-right">
              <h3 class="font-YekanBakh-Bold text-white mb-4 text-lg">دسترسی سریع</h3>
              <ul>
                  <li><a href="{% url "accounts:reset_password" %}">فراموشی رمز عبور</a></li>
              </ul>
          </div>
          <div class="col-span-6 lg:col-span-2 text-right">
              <h3 class="font-YekanBakh-Bold text-white mb-4 text-lg">خدمات</h3>
              <ul>
                  <li><a href="download.html">دانلودها</a></li>
                  <li><a href="invoices.html">صورتحساب ها</a></li>
                  <li><a href="reviews.html">نظرات</a></li>
                  <li><a href="chat.html">پیام ها</a></li>
                  {% if request.user.is_authenticated %}
                  <li><a href="{% url "accounts:profile" request.user.id%}">جزئیات حساب کاربری</a></li>
                  {% endif %}
                  <li><a href="{% url "doctor:signup_doctor" %}">همکاری با مجموعه</a></li>
              </ul>
          </div>
            <div class="col-span-12 lg:col-span-4">
                <h3 class="font-YekanBakh-Bold text-white mb-4 text-lg">عضویت در خبرنامه</h3>
                <div class="relative">
                  <input type="text" placeholder="username@site.com" class="input input-bordered w-full"> 
                  <button class="btn btn-primary absolute top-0 left-0 rounded-r-none">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5"></path>
                    </svg>
                    
                  </button>
                </div>
                <h3 class="font-YekanBakh-Bold text-white my-4 text-lg">ویزیت در شبکه های اجتماعی</h3>
                <div class="flex gap-4">
                  <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
                  <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a> 
                  <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
                </div>
            </div>

        </div>
    </div>
  </footer>

sites/templates/sites/header.html
{% load static %}

<section class="bg-white border-b px-4">
    <div class="container mx-auto max-w-screen-xl">
        <div class="flex justify-between items-center py-5">
          <div class="lg:hidden leading-none z-10">
            <div class="drawer">
                <input id="my-drawer-4" type="checkbox" class="drawer-toggle">
                <div class="drawer-content">
                    <label for="my-drawer-4" class="swap swap-rotate drawer-button">

                      <!-- this hidden checkbox controls the state -->
                      <input type="checkbox">
                      
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-black swap-off fill-current">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
                        </svg>
                        
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 stroke-black swap-on fill-current">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                        
                    </label> 
                  </div> 
                  <div class="drawer-side">
                    <label for="my-drawer-4" class="drawer-overlay"></label>
                    <ul class="menu p-4 w-80 h-full bg-base-200 text-base-content">
                      <div class="drawer-content text-left">
                          <label for="my-drawer-4" class="swap swap-rotate drawer-button">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                          </label> 
                        </div> 
                        <li><a class="hover:text-indigo-600" href="{% url "doctor:home" %}">صفحه اصلی</a></li>
                        <li><a class="hover:text-indigo-600" href="{% url "doctor:all_doctor" %}">لیست پزشکان</a></li>
                        <li><a class="hover:text-indigo-600" href="reservation.html">رزرو نوبت</a></li>
                        <li><a class="hover:text-indigo-600" href="{% url "blog:all_posts" %}">وبلاگ</a></li>
                        <li><a class="hover:text-indigo-600" href="{% url "sites:about_us" %}">درباره ما</a></li>
                        <li><a class="hover:text-indigo-600" href="{% url "sites:contact_us" %}">تماس با ما</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a class="hover:text-indigo-600" href="{% url 'accounts:logout' %}">خروج از حساب</a></li>
                        {% endif %}

                    </ul>
                  </div>
              </div>
        </div>
          <div class="flex items-center gap-8">
            <div>
                <a href="{% url "doctor:home" %}"><img src="/static/images/logo.png" alt=""></a>
            </div>
            <div class="hidden lg:block">
                <ul class="flex gap-x-8">
                    <li><a class="hover:text-indigo-600" href="{% url "doctor:home" %}">صفحه اصلی</a></li>
                    <li><a class="hover:text-indigo-600" href="{% url "doctor:all_doctor" %}">لیست پزشکان</a></li>
                    <li><a class="hover:text-indigo-600" href="reservation.html">رزرو نوبت</a></li>
                    <li><a class="hover:text-indigo-600" href="{% url "blog:all_posts" %}">وبلاگ</a></li>
                    <li><a class="hover:text-indigo-600" href="{% url "sites:about_us" %}">درباره ما</a></li>
                    <li><a class="hover:text-indigo-600" href="{% url "sites:contact_us" %}">تماس با ما</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a class="hover:text-indigo-600" href="{% url 'accounts:logout' %}">خروج از حساب</a></li>
                    {% endif %}
                </ul>
            </div>
          </div>
            <div class="border rounded-lg">
                {% if request.user.is_authenticated %}
                <a href="{% url "accounts:profile" request.user.id %}" class="flex py-2.5 px-5 rounded-lg hover:text-white hover:bg-stone-800 hover:transition hover:duration-700 hover:ease-in-out">سلام {{ request.user }}</a>
                {% else %}
                <a href="{% url "accounts:login" %}" class="flex py-2.5 px-5 rounded-lg hover:text-white hover:bg-stone-800 hover:transition hover:duration-700 hover:ease-in-out">ورود | ثبت نام</a>
                {% endif %}
            </div>
    
        </div>
    </div>
  </section>

sites/templates/sites/logo_description_footer.html
{% load static %}

<div class="leading-8">
    <img class="mb-4" src="/static/images/logo-footer.png" alt="">
        <p>{{ logo_desc_foot.abour_us_text }}</p>
  </div>

sites/templates/sites/sciol_about_us.html
{% for sciol in sciol_about_us %}
<div class="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 p-8 rounded-2xl mt-16">
    <div class="flex flex-col sm:flex-row justify-between items-center">
        <div class="text-white font-YekanBakh-ExtraBold text-lg">ما را در {{ sciol.title }} دنبال کنید...</div>
        <a href="{{ sciol.url }}"><div class="bg-white py-2 px-8 rounded-lg font-YekanBakh-ExtraBold text-lg">وارد شدن به {{ sciol.title }}</div></a>
    </div>
</div>
{% endfor %}

sites/templates/sites/slider.html
<section class="px-4">
    <div class="container mx-auto max-w-screen-2xl">
        <div class="relative">
            <div style="background-image: url(../assets/images/home-bg.png);" class="h-96 bg-no-repeat rounded-bl-3xl">
                <div class="bg-gradient-to-r from-sky-600 to-indigo-600 opacity-80 rounded-br-3xl rounded-bl-3xl">
                    <div class="flex flex-col items-center justify-center p-4 text-white leading-10 bg-[url('../../assets/images/noise.html')] h-96 mb-10">
                      <div id="typed-strings">
                        <p>مشاوره تلفنی</p>
                        <p>مشاوره متنی</p>
                      </div>
                      
                      <h2 class="text-2xl md:text-3xl font-YekanBakh-ExtraBold text-center"><span id="typed"></span>همین الان تجربه کن</h2>
                        </p>
                        <div class="relative w-72 lg:w-1/3 my-4">
                            <input type="text" placeholder="نام پزشک" class="input input-bordered w-full text-sm text-stone-600"> 
                            <button class="btn btn-primary absolute top-0 left-0 rounded-r-none">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"></path>
                                  </svg>
                                  
                            </button>
                          </div>
                          <p class="mt-4 text-sm md:text-base text-center leading-8">تا این لحظه از +1,200 شهر و روستا، از +27,100 پزشک ویزیت دریافت شده</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

sites/templates/sites/woc.html
<div>
    <div>
  
        <div class="flex items-center mb-4">
            <div class="bg-indigo-600 text-white rounded-xl rounded-bl-none p-2.5">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"></path>
                  </svg>                          
            </div>
            <h2 class="text-sm font-YekanBakh-ExtraBold mr-2">آدرس دفتر مرکزی:</h2>
            <p class="mr-2">{{ woc.address }}</p>

        </div>
        <div class="flex items-center mb-10">
          <div class="bg-indigo-600 text-white rounded-xl rounded-bl-none p-2.5">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"></path>
                </svg>                          
          </div>
          <h2 class="text-sm font-YekanBakh-ExtraBold mr-2">شماره تماس:</h2>
          <p class="mr-2">{{ woc.phone }} - {{ woc.landing_phone }}</p>

      </div>

      <div class="relative w-full h-60">
        <iframe class="absolute top-0 left-0 w-full h-full rounded-2xl" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25176.71364156464!2d51.32644191808706!3d35.71869708330613!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e00491ff3dcd9%3A0xf0b3697c567024bc!2sTehran%2C%20Tehran%20Province%2C%20Iran!5e0!3m2!1sen!2sus!4v1694067154680!5m2!1sen!2sus" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
        </iframe>
    </div>

    </div>
  </div>