blog/urls.py
from django.urls import path
from .views import AllPostBlog, BlogDetailsView, LatestBlogPostView


app_name = 'blog'
urlpatterns = [
    path('blog/', AllPostBlog.as_view(), name='all_posts'),
    path('blog_details/<slug:slug>/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),
    # path('all_category/', CategoryBlogView.as_view(), name='category'),
    path('latest_post/', LatestBlogPostView.as_view(), name='latest_post'),
    path('slug/<slug:category_slug>/', AllPostBlog.as_view(), name='post_by_category')
]

doctor/urls.py
from django.urls import path
from .views import  HomeComponents, SignUpDoctorView, All_doctor \
    ,DoctorSlider, LatesDoctor, AdvanceSearchDoctorView, AppointmentDoctorView, DetailsQuestionDoctorView

app_name = 'doctor'
urlpatterns = [
    path('', HomeComponents.as_view(), name='home'),
    path('signup_doctor/', SignUpDoctorView.as_view(), name='signup_doctor'),
    path('list_doctor/', All_doctor.as_view(), name='all_doctor'),
    # path('doctor_slider/', DoctorSlider.as_view(), name='doctor_slider'),
    path('latest_doctor', LatesDoctor.as_view(), name='latest_doctor'),
    # path('advance_search_doctor/', AdvanceSearchDoctorView.as_view(), name='advance_search_doctor'),
    path('details_doctor/<int:doctor_id>/', AppointmentDoctorView.as_view(), name='order_details_doctor'),
]

kine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('doctor.urls', namespace='doctor')),
    path('', include('sites.urls', namespace='sites')),
    path('', include('blog.urls', namespace='blog')),
    # path('', include('orders.urls', namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

doctor/models.py
from django.db import models
from django.template.defaultfilters import truncatewords
from django_jalali.db import models as jalali_models
from common.models import CreateAt, UpdateAt
from django.utils.translation import gettext_lazy as _


class Doctor(CreateAt, UpdateAt):
    user = models.OneToOneField('accounts.Users', on_delete=models.PROTECT, related_name='doctor')
    medical_system_code = models.CharField(_('Medical System Code'), max_length=10, unique=True)
    nation_code = models.CharField(_('National Code'), max_length=10, unique=True)
    address_doctor = models.TextField(_('Address'))
    image = models.ImageField(_('Image'), upload_to='doctors/%Y/%M/%d', width_field='with_image', height_field='height_image')
    with_image = models.PositiveIntegerField(editable=False, blank=True, null=True)
    height_image = models.PositiveIntegerField(editable=False, blank=True, null=True)
    doctor_birth_dat = models.DateField(_('Date of Birth milady'), null=True, blank=True)
    doctor_date_shamsi = jalali_models.jDateField(_('Date of Shamsi'), blank=True, null=True)
    is_active = models.BooleanField(_('Is Active'), default=False)
    reply_to = models.TextField(_('Reply to'), null=True, blank=True)
    skill = models.ManyToManyField('SkilDoctor', related_name='doctors')
    about_us_doctor = models.TextField(_('about us doctor'), null=True, blank=True)
    
    class Status(models.TextChoices):
        reject = 'rejected'
        accept = 'accept'
        wating = 'waiting'
    status = models.CharField(_("status send information"), max_length=8, choices=Status.choices, blank=True, null=True)
    
    class Gender(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')
    gender = models.CharField(_('Gender'), max_length=6, choices=Gender.choices)
    
    def __str__(self) -> str:
        return f'{self.user.get_full_name()} -- {self.medical_system_code}'
    
    class Meta:
        db_table = 'doctors'
        verbose_name = 'doctor'
        verbose_name_plural = 'doctors'


class SkilDoctor(CreateAt, UpdateAt):
    skill_name = models.CharField(_("skill doctor"), max_length=50)

    def __str__(self) -> str:
        return self.skill_name
    
    class Meta:
        db_table = 'skil_doctor'
        verbose_name = 'skil_doctor'
        verbose_name_plural = 'skil_doctor'


class ContactUs(CreateAt, UpdateAt):
    title = models.CharField(_('Title'), max_length=100)
    email = models.CharField(_('Email'), max_length=100)
    body = models.TextField(_('Body'))
    reply_to = models.TextField(_('Reply-To'))
    be_answered = models.BooleanField(_('Answered'), default=True)
    
    def __str__(self) -> str:
        return f'{self.title} -- {self.email}'
    
    class Meta:
        db_table = 'contact_us'
        verbose_name = 'contact us'
        verbose_name_plural = 'contact us'


class Communications(CreateAt, UpdateAt):
    address = models.TextField(_("Address"))
    
    class Meta:
        db_table = 'communications'
        verbose_name = 'communication'
        verbose_name_plural = 'communications'


class CommunicationPhone(CreateAt, UpdateAt):
    communication = models.ForeignKey('Communications', on_delete=models.CASCADE, related_name='phones')
    phone = models.CharField(_('Phone'), max_length=15, unique=True)
    
    class Meta:
        db_table = 'communication_phones'
        verbose_name = 'communication phone'
        verbose_name_plural = 'communication phones'


class Faq(CreateAt, UpdateAt):
    title = models.CharField(_('Title'), max_length=100)
    body = models.TextField(_('Body'))
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        db_table = 'faqs'
        verbose_name = 'faq'
        verbose_name_plural = 'faqs'


class QuestionDoctor(CreateAt):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='question_doctor')
    first_name = models.CharField(_('full name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=50)
    title = models.CharField(_('title'), max_length=100)
    body = models.TextField(_('body'))
    is_active = models.BooleanField(_('active'), default=False)

    def __str__(self):
        return self.title

    class Mata:
        db_table = 'question_doctor'
        verbose_name = 'question doctor'
        verbose_name_plural = 'question doctor'


class AnswerDoctor(CreateAt, UpdateAt):
    question = models.ForeignKey(QuestionDoctor, on_delete=models.CASCADE, related_name='question')
    body = models.TextField(_('body'))
    is_active = models.BooleanField(_('active'), default=False)

    def __str__(self):
        body_truncate = truncatewords(self.body, 30)
        return f'{self.question.full_name} -- {body_truncate}'

    class Meta:
        db_table = 'answer_doctor'
        verbose_name = 'answer doctor'
        verbose_name_plural = 'answer doctor'


class CardAppointmentDoctor(CreateAt, UpdateAt):
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE, related_name='appointments', blank=True,
                             null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='appointments_doctor_admin')
    from_time = jalali_models.jDateTimeField(_('from time'), unique=True)
    at_time = jalali_models.jDateTimeField(_('at time'), unique=True)
    price = models.PositiveIntegerField()
    cancel_description = models.TextField(_('cancel description'), blank=True, null=True)
    status = models.BooleanField(_('status'), default=True)

    def __str__(self):
        return  f'{self.doctor.user.get_full_name} -- {self.from_time} -- {self.at_time}'

    class Meta:
        db_table = 'card_appointment_doctor_admin'
        verbose_name = 'card_appointment_doctor_admin'
        verbose_name_plural = 'card_appointment_doctor_admin'

doctor/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views import View
from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .form import SignUpDoctorForm, QuestionDoctorForm
from .models import Doctor, CardAppointmentDoctor, QuestionDoctor


class HomeComponents(TemplateView):
    template_name = 'doctor/home.html'


class SignUpDoctorView(LoginRequiredMixin, View):
    from_class = SignUpDoctorForm
    template_name = 'doctor/signup_doctor.html'

    def get(self, request, *args, **kwargs):
        form = self.from_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.from_class(request.POST, request.FILES)
        if form.is_valid():
            Doctor.objects.create(user=request.user, **form.cleaned_data)
            messages.success(request, 'send information about you we called', 'success')
            return redirect('accounts:profile', request.user.id)
        return render(request, self.template_name, {'form': form})


class All_doctor(View):
    def get(self, request, *args, **kwargs):
        doctor = Doctor.objects.filter(is_active=True)
        return render(request, 'doctor/all_doctor.html', {'doctor': doctor})


class DoctorSlider(View):
    def get(self, request, *args, **kwargs):
        doctor = get_list_or_404(Doctor, is_active=True)[:10]
        doctor = Doctor.objects.filter(is_active=True)[:10]
        return render(request, 'doctor/doctor_slider.html', {'doctor': doctor})


class LatesDoctor(View):
    def get(self, request, *args, **kwargs):
        latest_doctor = Doctor.objects.filter(is_active=True)[:4]
        return render(request, 'doctor/latest_doctor.html', {'latest_doctor': latest_doctor})


class AdvanceSearchDoctorView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'doctor/advance_search_doctor.html')


class AppointmentDoctorView(View):
    template_name = 'doctor/details_doctor.html'

    def get(self, request, *args, **kwargs):
        details = Doctor.objects.get(id=kwargs['doctor_id'])
        return render(request, self.template_name, {'details': details})


class CardAppointmentView(View):
    template_name = 'doctor/card_appointment.html'

    def get(self, request, *args, **kwargs):
        appointments_user = CardAppointmentDoctor.objects.filter(status=True)
        return render(request, self.template_name, {'appointments_user': appointments_user})


class DetailsQuestionDoctorView(View):
    template_name = 'doctor/details_question_doctor.html'
    form_class = QuestionDoctorForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'سوال شما با موفقیت ساخته شد و پس از تایید به مایش در خواهد آمد', 'success')
            return redirect('doctor:home')
        return render(request, self.template_name, {'form': form})

doctor/templates/doctor/aboutus.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
<title>درباره ما</title>
{% endblock title %}

{% block content %}
<section class="px-6 mt-4 mb-8">
    <div class="container mx-auto max-w-screen-xl">
      <div class="bg-white p-3 rounded-3xl mb-4">
        <div class="text-sm breadcrumbs">
          <ul>
            <li><a>خانه</a></li> 
            <li>درباره ما</li>
          </ul>
        </div>
      </div>
      <div class="bg-white rounded-3xl p-6">
        <div class="p-3 bg-stone-200 rounded-xl mb-4">
          <h1 class="text-sm font-YekanBakh-Bold">درباره ما</h1>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-14 pt-8">
          <div class="leading-8">
            <h2 class="text-lg font-YekanBakh-Bold mb-4">درباره ویزیت بخوانید...</h2>

            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی گیرد.</p>
            <p class="mt-4">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
          </div>
          <div>
            <img class="rounded-2xl" src="/static/images/about-2.jpg" alt="">
          </div>
        </div>
        <div class="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 p-8 rounded-2xl mt-16">
          <div class="flex flex-col sm:flex-row justify-between items-center">
              <div class="text-white font-YekanBakh-ExtraBold text-lg">ما را در اینستاگرام دنبال کنید...</div>
              <a href="#"><div class="bg-white py-2 px-8 rounded-lg font-YekanBakh-ExtraBold text-lg">rtl-theme</div></a>
          </div>
      </div>
      </div>
    </div>
  </section>
{% endblock content %}

doctor/templates/doctor/advance_search_doctor.html
<div class="col-span-12 lg:col-span-3 lg:order-1">
    <div class="bg-white p-4 rounded-3xl mb-4 leading-8 sticky top-0">
      <div class="p-3 bg-stone-200 rounded-xl mb-4">
        <h1 class="text-sm font-YekanBakh-Bold">جستجو پیشرفته</h1>
      </div>
        <div>
          <label class="label">
            <span class="label-text-alt">نام پزشک:</span>
          </label>
          <input type="text" placeholder="نام متخصص" class="input input-bordered w-full rounded-xl placeholder:text-xs">   
          <label class="label">
            <span class="label-text-alt">تخصص و فوق تخصص:</span>
          </label>
          <input type="text" placeholder="تخصص" class="input input-bordered w-full rounded-xl placeholder:text-xs"> 
          <label class="label">
            <span class="label-text-alt">استان:</span>
          </label>
          <select class="select select-bordered w-full pr-3">
            <option selected="">تهران</option>
            <option>اصفهان</option>
            <option>شیراز</option>
            <option>گیلان</option>
            <option>کرج</option>
          </select>
          <label class="label">
            <span class="label-text-alt">جنسیت:</span>
          </label>
          <div class="form-control">
            <label class="label cursor-pointer">
              <span class="label-text">خانم</span> 
              <input type="radio" name="radio-10" class="radio checked:bg-red-500" checked="">
            </label>
          </div>
          <div class="form-control">
            <label class="label cursor-pointer">
              <span class="label-text">آقا</span> 
              <input type="radio" name="radio-10" class="radio checked:bg-blue-500">
            </label>
          </div>
          <button class="btn bg-stone-800 w-full hover:bg-stone-900 text-white my-3">جستجو</button> 
        </div>
        
    </div>
</div>

doctor/templates/doctor/all_doctor.html
{% extends "base/base.html" %}

{% load render_partial %}

{% load static %}

{% block title %}
    <title>دکترها</title>
{% endblock title %}

{% block content %}
<div class="grid grid-cols-12 gap-4">
  <div class="col-span-12 lg:col-span-9 lg:order-2">
      <div class="flex flex-col gap-4">
          {% for all_doctor in doctor %}
          <div class="bg-white p-8 rounded-3xl">
            <div class="flex flex-col lg:flex-row items-center justify-between">
                <div class="flex items-center mb-8 lg:mb-0">
                    <div class="avatar online">
                        <div class="w-20 rounded-full">
                          <img src="{{ all_doctor.image.url }}">
                        </div>
                      </div>
                      <div class="mr-4">
                      <h3 class="font-YekanBakh-ExtraBold text-base mb-2">{{ all_doctor.user.get_full_name }}</h3> 
                      <p class="text-gray-500">{% for s in all_doctor.skill.all %}{{ s }}{% if not forloop.last %}-{% endif %}{% endfor %}</p>
                      </div>
                </div>
                <div class="flex items-center gap-4">
                    <div class="text-yellow-500 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                            <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                          </svg>
                          <span class="font-YekanBakh-SemiBold">4.8</span>
                    </div>
                    <div class="text-green-500 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"></path>
                          </svg>
                        <span class="font-YekanBakh-SemiBold">96 درصد پیشنهاد</span>                                  
                    </div>
                    <span class="font-YekanBakh-SemiBold">2733 نظر</span>
                </div>
            </div>
            <div class="bg-gray-50 leading-8 p-4 my-6 rounded-2xl">
                <div class="flex flex-col md:flex-row items-center">
                    <span class="text-sm font-YekanBakh-Bold">خدمات:</span>
                    <div class="mr-1">{% for s in all_doctor.skill.all %}{{ s }}{% if not forloop.last  %},{% endif %}{% endfor %}</div>
                </div>
                <div class="flex gap-8">
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.25 9.75v-4.5m0 4.5h4.5m-4.5 0l6-6m-3 18c-8.284 0-15-6.716-15-15V4.5A2.25 2.25 0 014.5 2.25h1.372c.516 0 .966.351 1.091.852l1.106 4.423c.11.44-.054.902-.417 1.173l-1.293.97a1.062 1.062 0 00-.38 1.21 12.035 12.035 0 007.143 7.143c.441.162.928-.004 1.21-.38l.97-1.293a1.125 1.125 0 011.173-.417l4.423 1.106c.5.125.852.575.852 1.091V19.5a2.25 2.25 0 01-2.25 2.25h-2.25z"></path>
                        </svg>                                      
                        <div class="mr-1">مشاوره تلفنی</div>
                    </div>
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"></path>
                          </svg>                                                                      
                        <div class="mr-1">مشاوره متنی</div>
                    </div>
                </div>
            </div>
            <div class="flex flex-col md:flex-row leading-8 items-center justify-between">
                <div class="flex flex-col md:flex-row items-center mb-6 md:mb-0">
                    <span class="text-sm font-YekanBakh-Bold">آدرس:</span>
                    <div class="mr-1">{{ all_doctor.address_doctor }}</div>
                </div>
                <div>
                    <a href="{% url 'doctor:order_details_doctor' all_doctor.id %}" class="bg-indigo-600 hover:bg-indigo-700 hover:transition hover:duration-700 p-6 py-2 text-center rounded-xl text-white">دریافت مشاوره</a>
                </div>
            </div>

        </div>
          {% endfor %}

      </div>
  </div>
  {% render_partial 'doctor.views.AdvanceSearchDoctorView' %}
</div>
{% endblock content %}

doctor/templates/doctor/details_question_doctor.html
<div class="bg-white rounded-3xl p-6">
    <div class="p-3 bg-stone-200 rounded-xl mb-4">
        <h1 class="text-sm font-YekanBakh-Bold">پرسش و پاسخ</h1>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <form action="" method="POST">
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="ارسال سوال" class="btn bg-stone-800 w-36 hover:bg-stone-900 text-white my-3">
        </form>
    </div>
</div>

doctor/templates/doctor/doctor_slider.html
<div class="swiper doctor-slider swiper-initialized swiper-horizontal swiper-rtl swiper-backface-hidden">
    {% for d in doctor %}
    <div class="swiper-wrapper" id="swiper-wrapper-8bb2e184945b75cb" aria-live="off" style="transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); transition-delay: 0ms;">
      <div class="swiper-slide swiper-slide-active" role="group" aria-label="1 / 7" style="width: 218.8px; margin-left: 15px;">
        <div class="bg-white rounded-3xl leading-10">
            <div class="flex flex-col items-center justify-center p-4">
                <div class="avatar online">
                    <div class="w-20 rounded-full">
                      <img src="{{ d.image.url }}">
                    </div>
                  </div>
                  <h3 class="font-YekanBakh-ExtraBold mt-4 text-base">{{ d.user.get_full_name }}</h3> 
                  {% for skill in d.skill.all %}
                  <p>{{ skill }}{% if not forloop %},{% endif %}</p>
                  {% endfor %}
                  <div class="text-yellow-500 flex mt-2">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
                        <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd"></path>
                      </svg>
                      
                  </div>
                  <a href="{% url 'doctor:order_details_doctor' d.id %}" class="border hover:bg-amber-100 hover:transition hover:duration-700 p-1 w-full mt-4 text-center rounded-xl">دریافت مشاوره</a>
            </div>
          </div>
      </div>
      {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
  <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>