accounts/urls.py
from django.urls import path
from .views import (UserSignupView, LoginViews, AcceptCodeView, ProfileView, LogOutView \
    ,UserPasswordResetView, UserPasswordResetCompleteView, UserPasswordResetConfirmView, UserPasswordResetDoneView,
                    EditProfileView)
app_name = 'accounts'
urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', LoginViews.as_view(), name='login'),
    path('accept_code/', AcceptCodeView.as_view(), name='accept_code'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='edit_profile'),
    path('profile/logout/', LogOutView.as_view(), name='logout'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import AllPostBlog, BlogDetailsView, LatestBlogPostView


app_name = 'blog'
urlpatterns = [
    path('blog/', AllPostBlog.as_view(), name='all_posts'),
    path('blog_details/<slug:slug>/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),
    # path('all_category/', CategoryBlogView.as_view(), name='category'),
    path('latest_post/', LatestBlogPostView.as_view(), name='latest_post'),
    path('slug/<slug:category_slug>/', AllPostBlog.as_view(), name='post_by_category')
]

kine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('doctor.urls', namespace='doctor')),
    path('', include('sites.urls', namespace='sites')),
    path('', include('blog.urls', namespace='blog')),
    # path('', include('orders.urls', namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.validators import UnicodeUsernameValidator
from .managers import UserManager, SoftDeleteManager
from common.models import CreateAt, UpdateAt


class Users(AbstractBaseUser, PermissionsMixin, UpdateAt, CreateAt):
    first_name = models.CharField(_('First Name'), max_length=100)
    last_name = models.CharField(_('Last Name'), max_length=100)
    email = models.EmailField(_('Email Address'), unique=True)
    is_active = models.BooleanField(_('Active'), default=False)
    is_staff = models.BooleanField(_('Staff'), default=False)
    is_deleted = models.BooleanField(_('delete user'), editable=False, default=False)
    deleted_at = models.DateTimeField(_('deleted at'), editable=False, blank=True, null=True)
    random_active_code = models.CharField(_('random active code'), max_length=72, blank=True, null=True, editable=False)
    image = models.ImageField(_('image'), upload_to='images/user/%Y/%M/%d', width_field='width_image',
                              height_field='height_image', blank=True, null=True)
    width_image = models.IntegerField(_('width'), blank=True, null=True)
    height_image = models.IntegerField(_('height'), blank=True, null=True)
    about_us = models.TextField(_('about us'), blank=True, null=True)

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects = UserManager()
    soft_delete_manager = SoftDeleteManager()

    def __str__(self) -> str:
        return self.get_full_name()

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class UserDelete(Users):
    class Meta:
        proxy = True
        auto_created = True


class Notofication(CreateAt):
    title = models.CharField(_('Title'), max_length=100)
    body = models.TextField(_('Body'))

    def __str__(self) -> str:
        return self.title

    class Meta:
        db_table = 'notifications'
        verbose_name = 'notification'
        verbose_name_plural = 'notifications'


class OtpCode(CreateAt):
    code = models.PositiveIntegerField()
    email = models.EmailField(_('Email'), unique=True)

    def __str__(self) -> str:
        return f'{self.code} - {self.email} - {self.create_at}'

    class Meta:
        db_table = 'otp_codes'
        verbose_name = 'otp code'
        verbose_name_plural = 'otp code'

accounts/views.py
from typing import Any
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from random import randint
from .models import Users, OtpCode
from .form import SignUpForm, LoginForm, AcceptCodeForm, PasswordResetForms, EditProfile
from kine.utils import send_code_email


class UserSignupView(View):
    form_class = SignUpForm
    template_name = 'accounts/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('doctor:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            random_number = randint(1000000, 9999999)
            send_code_email(cd['email'], random_number)
            OtpCode.objects.create(email=cd['email'], code=random_number)
            request.session['user_signup_info'] = {
                'email': cd['email'],
                'username': cd['username'],
                'password': cd['password']
            }
            messages.success(request, 'created account successfully please enter code for active accounts', 'success')
            return redirect('accounts:accept_code')
        return render(request, self.template_name, {'form': form})


class AcceptCodeView(View):
    form_class = AcceptCodeForm
    template_name = 'accounts/accept_code.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        user_session = request.session['user_signup_info']
        otp_code = OtpCode.objects.get(email=user_session['email'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if int(cd['code']) == otp_code.code:
                Users.objects.create_user(
                    email=user_session['email'],
                    password=user_session['password'],
                    username=user_session['username']
                )
                del user_session
                otp_code.delete()
                messages.success(request, 'you have successfully verify accounts', 'success')
                return redirect('accounts:login')
            else:
                messages.error(request, 'your code is invalid', 'danger')
                return render(request, self.template_name, {'form': form})
        return render(request, self.template_name, {'form': form})


class LoginViews(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('accounts:profile', request.user.id)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'login successful', 'success')
                return redirect('accounts:profile', request.user.id)
            messages.error(request, 'login failed', 'danger')
        return render(request, self.template_name, {'form': form})


class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'


class LogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'successfly logout request', 'success')
        return redirect('accounts:login')


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'
    form_class = PasswordResetForms


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class ProfileView(View):
    def get(self, request, *args, **kwargs):
        profile = get_object_or_404(Users, pk=kwargs['pk'])
        return render(request, 'accounts/profile.html', {'profile': profile})


class EditProfileView(LoginRequiredMixin, View):
    form_class = EditProfile
    template_name = 'accounts/edit_profile.html'

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.user_instance = get_object_or_404(Users, pk=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = self.user_instance
        form = self.form_class(instance=user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        user = self.user_instance
        form = self.form_class(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'successfully update profile', 'success')
            return redirect('accounts:profile', pk=request.user.id)
        return render(request, self.template_name, {'form': form})

accounts/templates/accounts/accept_code.html
{% extends "base/base.html" %}

{% block title %}
<title>accept code</title>
{% endblock title %}

{% block content %}
<section class="h-screen px-4 flex items-center">
    <div class="container mx-auto max-w-screen-lg">
        <div class="bg-white rounded-2xl overflow-hidden">
            <div class="flex flex-col md:flex-row gap-8">
                <div class="flex-1 p-8 md:p-4 lg:p-20 lg:pb-0">
                    <form action="" method='POST'>
                        {% csrf_token %}
                        <h2 class="text-3xl font-YekanBakh-ExtraBlack my-4">تایید حساب کاربر</h2>
                        {{ form }}
                        <button type='submit' class="btn bg-stone-800 hover:bg-stone-900 text-white w-full my-4">تایید کاربر</button>
                    </form>
                </div>
                <div class="hidden md:block">
                    <img class="bg-cover" src="/static/images/login.jpg" alt="" style="width: 18rem; height: 40rem;">
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/edit_profile.html
{% extends "base/base.html" %}

{% load thumbnail %}

{% block title %}
<title>ویرایش پروفایل</title>
{% endblock title %}

{% block content %}
<div class="bg-white p-4 lg:p-8 rounded-3xl w-full">
    <div class="p-3 bg-stone-200 rounded-xl mb-4">
        <h1 class="text-sm font-YekanBakh-Bold">ویرایش حساب کاربری</h1>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
            <form action='' method='post' enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                {% thumbnail request.user.image '250' crop='center' as im %}
                  <img src="{{ im.url }}" width='{{ im.width }}' height='{{ im.height }}' alt="User Image Preview, defualt image" class="mb-4 rounded-lg">
                {% endthumbnail %}
                <button type='submit' class="btn bg-stone-800 w-36 hover:bg-stone-900 text-white my-3">ذخیره تغییرات</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base/base.html" %}

{% block title %}
    <title>ورود</title>
{% endblock title %}

{% block content %}
<section class="h-screen px-4 flex items-center">
    <div class="container mx-auto max-w-screen-lg">
        <div class="bg-white rounded-2xl overflow-hidden">
            <div class="flex flex-col md:flex-row gap-8">
                <div class="flex-1 p-8 md:p-4 lg:p-20 lg:pb-0">
                    <form action="" method='POST'>
                        <h2 class="text-3xl font-YekanBakh-ExtraBlack my-4">ورود</h2>
                        {% csrf_token %}
                        {{ form }}
                        <button type='submit' class="btn bg-stone-800 hover:bg-stone-900 text-white w-full my-4">ورود</button>
                    </form>
                    <p class="text-center my-4">رمز عبور خود را <a href="{% url "accounts:reset_password" %}"><strong>فراموش</strong> </a>کرده اید؟</p>
                    <div class="divider my-8">یا</div>
                    <p class="text-center my-4"><a href="{% url "accounts:signup" %}">حساب کاربری ندارید !!!</a></p>
                </div>
                <div class="hidden md:block">
                    <img class="bg-cover w-18r" src="/static/images/login.jpg" alt="" style="width: 18rem;">
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/notification.html
<h1 class="text-sm font-YekanBakh-Bold">اطلاعیه مهم</h1>
<div class="bg-white border p-6 rounded-2xl">
    <div class="flex flex-col md:flex-row items-center justify-between gap-4">
        <div class="leading-8 mr-2">
            <p class="text-sm font-YekanBakh-Bold">عنوان اطلاعیه خیلی مهم</p>
            <span class="text-xs text-stone-500">دوشنبه ۲۰ ام شهریور ۱۴۰۲</span>
            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
        </div>
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-14 h-14 text-stone-200">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0M3.124 7.5A8.969 8.969 0 015.292 3m13.416 0a8.969 8.969 0 012.168 4.5"></path>
              </svg>
              
        </div>
    </div>

</div>

accounts/templates/accounts/password_reset_complete.html
{% extends 'base/base.html' %}

{% block content %}
  <p>your password changed.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/profile.html
{% extends "base/base.html" %}

{% block title %}
    <title>{{ request.user }}</title>
{% endblock title %}

{% block content %}
<section class="px-6 mt-4">
    <div class="container mx-auto max-w-screen-2xl">
        <div class="flex gap-4">
            <div class="w-96 bg-white rounded-3xl overflow-hidden hidden lg:block">
                <div class="h-24 bg-indigo-500 relative">
                    <div class="text-center absolute right-[6.3rem]">
                        <div class="avatar online mt-8">
                            <div class="w-24 rounded-full">
                                {% if profile.image %}
                                    <img src="{{ profile.image.url }}">
                                {% endif %}
                            </div>
                          </div>
                           
                      <h1 class="text-sm font-YekanBakh-Bold mt-4">{{ profile.get_full_name }}</h1>
                    </div>
                </div>

                <nav class="mt-24">
                  {% if request.user.is_superuser %}
                    <a href="/admin" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z"></path>
                        </svg>     
                      <span class="mr-1">پنل ادمین</span>
                    </a>
                  {% endif %}
                  <a href="my-account.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z"></path>
                        </svg>     
                      <span class="mr-1">پیشخوان</span>
                  </a>
                   <a href="{% url "accounts:logout" %}" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5"></path>
                        </svg>

                      <span class="mr-1">نوبت ها</span>
                  </a>
                  <a href="download.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3 3m0 0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"></path>
                        </svg>
                          
                      <span class="mr-1">دانلود ها</span>
                  </a>
                  <a href="invoices.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z"></path>
                        </svg>
                          
                      <span class="mr-1">صورتحساب ها</span>
                  </a>
                  <a href="reviews.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"></path>
                        </svg>
                            
                      <span class="mr-1">نظرات</span>
                  </a>
                  <a href="chat.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"></path>
                        </svg>
                           
                      <span class="mr-1">پیام ها</span>
                  </a>
                  <a href="edit-account.html" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"></path>
                        </svg>
                            
                      <span class="mr-1">جزئیات حساب کاربری</span>
                  </a>
                  <a href="{% url "accounts:logout" %}" class="flex items-center py-4 px-8 hover:bg-stone-100 duration-300">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5"></path>
                        </svg>
                             
                      <span class="mr-1">خروج</span>
                  </a>
              </nav>
            </div>
            <div class="bg-white p-4 lg:p-8 rounded-3xl w-full">
                <div class="p-3 bg-stone-200 rounded-xl mb-4">
                    <h1 class="text-sm font-YekanBakh-Bold">حساب کاربری</h1>
                  </div>
                  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label class="label">
                            <span class="label-text-alt">نام:</span>
                          </label>
                          <strong>{{ profile.first_name }}</strong>
                    </div>
                    <div>
                        <label class="label">
                            <span class="label-text-alt">نام خانوادگی:</span>
                          </label>
                          <strong>{{ profile.last_name }}</strong>
                    </div>
                    <div>
                        <label class="label">
                            <span class="label-text-alt">نام نمایشی:</span>
                          </label>
                          <strong>{{ profile.get_full_name }}</strong>
                    </div>
                    <div>
                        <label class="label">
                            <span class="label-text-alt">آدرس ایمیل:</span>
                          </label>
                          <strong>{{ profile.email }}</strong>
                    </div>
                    <div>
                        <label class="label">
                            <span class="label-text-alt">گذرواژه :</span>
                          </label>
                          <strong>***</strong>
                    </div>
                    <div>
                        <label class="label">
                            <span class="label-text-alt"> نام کاربری:</span>
                          </label>
                          <strong>{{ profile.username }}</strong>
                    </div>
                    <div>
                      <label class="label">
                          <span class="label-text-alt"> آخرین ورود:</span>
                        </label>
                        <strong>{{ profile.last_login }}</strong>
                      </div>
                    {% if request.user.is_authenticated %}
                    <a href='{% url "accounts:edit_profile" request.user.id %}' class="btn bg-stone-800 w-36 hover:bg-stone-900 text-white my-3">ویرایش اطلاعات</a>
                    {% endif %}
                  </div>
                  <div>
                    <label class="label">
                        <span class="label-text-alt">درباره من :</span>
                      </label>
                      <strong>{% if profile.about_us %}{{ profile.about_us }}{% else %}هنوز چیزی در این جا وارد نکرده اید{% endif %}</strong>
                </div>
            </div>
          </div>
      </div>
</section>
{% endblock  %}